version: '3'

services:
  ana-dev:
    container_name: ana-dashboard
    image: iita/ana-dashboard:${DEV_TAG}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=your_secret_key

  ana-prod:
    container_name: ana-dashboard
    image: iita/ana-dashboard:${PROD_TAG}
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8001"
    environment:
      - DEBUG=0
      - SECRET_KEY=production_secret_key