version: '3'

services:
  ana:
    container_name: ana-dev
    image: iita/ana-dashboard
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=your_secret_key
  ana-prod:
    container_name: ana-prod
    image: iita/ana-dashboard:production
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=your_secret_key
