version: '3'

services:
  ana-dev:
    container_name: ana-dev
    image: iita/ana-dashboard:${DEV_TAG}
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./static:/app/static
    ports:
      - "8000:8000"
    environment:
      DEBUG: 0
      SECRET_KEY: dev_secret_key
      DJANGO_CSRF_TRUSTED_ORIGINS: 'http://localhost:8000'
    restart: unless-stopped

  ana-prod:
    container_name: ana-prod
    image: iita/ana-dashboard:${PROD_TAG}
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - ./static:/app/static
    ports:
      - "8005:8000"
    environment:
      DEBUG: 0
      SECRET_KEY: production_secret_key
      DJANGO_CSRF_TRUSTED_ORIGINS: 'http://localhost:8000'
    restart: unless-stopped

  frontend:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/static:ro
    depends_on:
      - ana-prod