# Generated by Django 4.2.3 on 2023-07-24 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_dissemination_farmers_f'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dissemination',
            name='Latitude',
        ),
        migrations.RemoveField(
            model_name='dissemination',
            name='Longitude',
        ),
    ]
