# Generated by Django 4.2.3 on 2023-11-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_partner_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='digital_services',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='financial_services',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='input_supply',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='integrated',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='marketing_processing',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='mel_data',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='policy_regulation',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='production',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='research',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
