# Generated by Django 4.2.3 on 2023-11-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_extensionagents'),
    ]

    operations = [
        migrations.AddField(
            model_name='extensionagents',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
