# Generated by Django 4.2.3 on 2023-11-03 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_eventparticipants'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipants',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
