# Generated by Django 4.2.3 on 2023-11-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_eventparticipants_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('firstname', models.CharField(blank=True, max_length=100, null=True)),
                ('lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('org', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('event', models.CharField(blank=True, max_length=100, null=True)),
                ('partner', models.CharField(blank=True, max_length=100, null=True)),
                ('partner_original', models.CharField(blank=True, max_length=100, null=True)),
                ('hasc1', models.CharField(max_length=120, null=True)),
                ('hasc2', models.CharField(max_length=120, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('venue', models.CharField(max_length=100, null=True)),
                ('lat', models.CharField(max_length=100, null=True)),
                ('lon', models.CharField(max_length=100, null=True)),
                ('date_added', models.DateField()),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('usecase', models.CharField(blank=True, max_length=50, null=True)),
                ('format', models.CharField(blank=True, max_length=50, null=True)),
                ('titlefull', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('topics', models.CharField(blank=True, max_length=255, null=True)),
                ('services', models.CharField(max_length=100, null=True)),
                ('input_type', models.CharField(blank=True, max_length=100, null=True)),
                ('input_orgs', models.CharField(blank=True, max_length=100, null=True)),
                ('credit_types', models.CharField(blank=True, max_length=100, null=True)),
                ('credit_orgs', models.CharField(blank=True, max_length=100, null=True)),
                ('market_type', models.CharField(blank=True, max_length=100, null=True)),
                ('market_orgs', models.CharField(max_length=100, null=True)),
                ('paper', models.CharField(max_length=100, null=True)),
                ('app', models.BooleanField(default=False, null=True)),
                ('viamo', models.BooleanField(default=False, null=True)),
                ('arifu', models.BooleanField(default=False, null=True)),
                ('fr', models.BooleanField(default=False, null=True)),
                ('ic', models.BooleanField(default=False, null=True)),
                ('wm_pp', models.BooleanField(default=False, null=True)),
                ('sp_hs', models.BooleanField(default=False, null=True)),
                ('input', models.BooleanField(default=False, null=True)),
                ('credit', models.BooleanField(default=False, null=True)),
                ('market', models.BooleanField(default=False, null=True)),
                ('fertilizer_supply', models.BooleanField(default=False, null=True)),
                ('herbicide_supply', models.BooleanField(default=False, null=True)),
                ('cuttings_supply', models.BooleanField(default=False, null=True)),
                ('mechanization', models.BooleanField(default=False, null=True)),
                ('indirect_financial', models.BooleanField(default=False, null=True)),
                ('individual_credit', models.BooleanField(default=False, null=True)),
                ('group_lending', models.BooleanField(default=False, null=True)),
                ('intermediary_credit', models.BooleanField(default=False, null=True)),
                ('market_information', models.BooleanField(default=False, null=True)),
                ('market_access', models.BooleanField(default=False, null=True)),
                ('crop_insurance', models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
