# Generated by Django 4.2.3 on 2023-11-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_events_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='date_added',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='enddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='startdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
