# Generated by Django 4.2.3 on 2023-11-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_farmers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmers',
            name='farm_area',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
