# Generated by Django 4.2.3 on 2023-11-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_dissemination_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=100)),
                ('partner', models.CharField(blank=True, max_length=100)),
                ('partnerfull', models.CharField(blank=True, max_length=100)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('partner_type', models.CharField(blank=True, max_length=100)),
                ('vc_segmain', models.CharField(blank=True, max_length=100)),
                ('vc_segs', models.CharField(blank=True, max_length=100)),
                ('integrated', models.BooleanField(default=True)),
                ('mel_data', models.BooleanField(default=False)),
                ('input_supply', models.BooleanField(default=False)),
                ('production', models.BooleanField(default=False)),
                ('digital_services', models.BooleanField(default=False)),
                ('marketing_processing', models.BooleanField(default=False)),
                ('financial_services', models.BooleanField(default=False)),
                ('research', models.BooleanField(default=False)),
                ('policy_regulation', models.BooleanField(default=False)),
            ],
        ),
    ]
