# Generated by Django 4.2.3 on 2023-11-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='index',
            field=models.IntegerField(default=None),
        ),
    ]
