# Generated by Django 4.2.3 on 2023-11-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_events_date_added_alter_events_enddate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('partner', models.CharField(blank=True, max_length=100, null=True)),
                ('firstname', models.CharField(blank=True, max_length=100, null=True)),
                ('lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=100, null=True)),
                ('own_phone', models.BooleanField(default=False)),
                ('crops', models.CharField(blank=True, max_length=50, null=True)),
                ('crops_other', models.CharField(max_length=50, null=True)),
                ('farm_area', models.DecimalField(blank=True, decimal_places=1, max_digits=2)),
                ('area_unit', models.CharField(blank=True, max_length=50)),
                ('cassava', models.BooleanField(default=False)),
                ('yam', models.BooleanField(default=False)),
                ('maize', models.BooleanField(default=False)),
                ('rice', models.BooleanField(default=False)),
                ('sorghum', models.BooleanField(default=False)),
            ],
        ),
    ]
