# Generated by Django 4.2.3 on 2023-11-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_farmers_farm_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmers',
            name='area_unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='farmers',
            name='cassava',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='farmers',
            name='maize',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='farmers',
            name='rice',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='farmers',
            name='sorghum',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='farmers',
            name='yam',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
