# Generated by Django 4.2.3 on 2023-11-03 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_alter_farmers_area_unit_alter_farmers_cassava_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmers',
            name='own_phone',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
