# Generated by Django 4.2.3 on 2024-02-25 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_alter_farmers_own_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmers',
            name='own_phone',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True),
        ),
    ]
